"""statement_uploads and transactions

The two tables statement imports write (SPEC §5, Phase 1 Step 7).

Autogenerated with `alembic revision --autogenerate` from the models and
then reviewed (CLAUDE.md rule 7). Worth knowing when reading it:

- `uq_statement_uploads_user_id_file_sha256` is dedupe level 1 and
  `uq_transactions_account_id_fingerprint` is dedupe level 2 (SPEC §6.3).
  The import relies on the second one for `ON CONFLICT DO NOTHING`.
- The enum columns are VARCHAR + CHECK, not native Postgres ENUMs, so
  adding a value later is a one-line migration (ADR 002).
- `ix_transactions_user_txn_date_id` is deliberately DESC on both sorted
  columns: it is the index `GET /transactions` pages through (Step 8).
  `sa.literal_column` is how Alembic writes "that column, descending".
- The trigram GIN index needs the `pg_trgm` extension, which migration
  0001 already created.

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-05
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "statement_uploads",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column(
            "file_type",
            sa.Enum(
                "csv",
                "xls",
                "pdf",
                name="file_type",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "needs_password",
                "needs_review",
                "completed",
                "failed",
                name="upload_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("rows_parsed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rows_inserted", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rows_duplicate", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reconciliation_errors", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "file_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_statement_uploads_file_sha256_hex")
        ),
        sa.CheckConstraint(
            "rows_parsed >= 0 AND rows_inserted >= 0 AND rows_duplicate >= 0 "
            "AND reconciliation_errors >= 0",
            name=op.f("ck_statement_uploads_counts_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_statement_uploads_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_statement_uploads_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statement_uploads")),
        sa.UniqueConstraint(
            "user_id", "file_sha256", name=op.f("uq_statement_uploads_user_id_file_sha256")
        ),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("upload_id", sa.Uuid(), nullable=False),
        sa.Column("txn_date", sa.Date(), nullable=False),
        sa.Column("value_date", sa.Date(), nullable=True),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum(
                "debit",
                "credit",
                name="direction",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("balance_after_paise", sa.BigInteger(), nullable=True),
        sa.Column("raw_description", sa.Text(), nullable=False),
        sa.Column("normalized_description", sa.Text(), nullable=False),
        sa.Column(
            "channel",
            sa.Enum(
                "upi",
                "card",
                "neft",
                "imps",
                "rtgs",
                "atm",
                "cheque",
                "ach_nach",
                "interest",
                "charges",
                "other",
                name="channel",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="other",
            nullable=False,
        ),
        sa.Column("counterparty_vpa", sa.Text(), nullable=True),
        sa.Column("merchant_id", sa.Uuid(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column(
            "category_source",
            sa.Enum(
                "user_manual",
                "user_rule",
                "merchant",
                "keyword",
                "llm",
                "heuristic",
                "none",
                name="category_source",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            server_default="none",
            nullable=False,
        ),
        sa.Column("category_confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column(
            "is_self_transfer", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_paise > 0", name=op.f("ck_transactions_amount_positive")),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("fk_transactions_account_id_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_transactions_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
            name=op.f("fk_transactions_merchant_id_merchants"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["statement_uploads.id"],
            name=op.f("fk_transactions_upload_id_statement_uploads"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_transactions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint(
            "account_id", "fingerprint", name=op.f("uq_transactions_account_id_fingerprint")
        ),
    )
    op.create_index(
        "ix_transactions_normalized_description_trgm",
        "transactions",
        ["normalized_description"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"normalized_description": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_transactions_user_category_date",
        "transactions",
        ["user_id", "category_id", "txn_date"],
        unique=False,
    )
    op.create_index(
        "ix_transactions_user_merchant", "transactions", ["user_id", "merchant_id"], unique=False
    )
    op.create_index(
        "ix_transactions_user_txn_date_id",
        "transactions",
        ["user_id", sa.literal_column("txn_date DESC"), sa.literal_column("id DESC")],
        unique=False,
    )


def downgrade() -> None:
    # Indexes are dropped before their table only because Alembic writes
    # the reverse of the upgrade; DROP TABLE would remove them anyway.
    # transactions goes first: it has the foreign keys into
    # statement_uploads.
    op.drop_index("ix_transactions_user_txn_date_id", table_name="transactions")
    op.drop_index("ix_transactions_user_merchant", table_name="transactions")
    op.drop_index("ix_transactions_user_category_date", table_name="transactions")
    op.drop_index(
        "ix_transactions_normalized_description_trgm",
        table_name="transactions",
        postgresql_using="gin",
        postgresql_ops={"normalized_description": "gin_trgm_ops"},
    )
    op.drop_table("transactions")
    op.drop_table("statement_uploads")
